### ISSUE TITLE
VCF_to_Seq_diploid.pl trimming error

### ISSUE THREAD

**Issue by peterdfields** [justin-lack/Drosophila-Genome-Nexus#1]
In using the pipeline everything looks fine until I arrive at this step. While the VCF files look okay and have the correct reference length, when I run the VCF_to_Seq_diploid.pl script the resulting sequence files are severely shortened, from ~ 160kb down to 20kb or less in some cases. Using vcf-consensus on the updated reference results in the correct output length, though the script I guess is doing quite a lot more concerning masking and so forth. I can provide sample vcf files if that would help determine what may be going wrong.

**Comment by justin-lack** [comment]
Please send me an example vcf (the input for the script) as well as a sample of the script you are using as input into the IndelShift.pl script. Also, are you running this on a different taxon than D. melanogaster? If so, which taxon and which reference are you mapping to?

Justin Lack Ph.D.
Laboratory of Genetics
University of Wisconsin
425-G Henry Mall
Madison, WI 53706
jlack@wisc.edu
405-314-4356
